image:
  - Visual Studio 2019

install:
  - choco install gitversion.portable -y

assembly_info:
  patch: false
  
before_build:
  - nuget restore
  - gitversion /l console /output buildserver /updateAssemblyInfo

platform:
  - Any CPU

configuration:
  - Release
 
build:
  project: ConventionTests.sln

after_build:
  - cmd: dotnet pack TestStack.ConventionTests\TestStack.ConventionTests.csproj -c Release -o .\artifacts --include-symbols
  - cmd: dotnet pack TestStack.ConventionTests.Autofac\TestStack.ConventionTests.Autofac.csproj -c Release -o .\artifacts --include-symbols

artifacts:
  - path: '.\aritifacts\*.nupkg'

#  - cmd: appveyor PushArtifact "TestStack.ConventionTests.%GitVersion_NuGetVersion%.nupkg"
#  - cmd: appveyor PushArtifact "TestStack.ConventionTests.Autofac.%GitVersion_NuGetVersion%.nupkg"
